(dp1
S'output'
p2
S"<class '_mysql_exceptions.OperationalError'> (1305, 'FUNCTION reques.args does not exist')"
p3
sS'layer'
p4
S'D:\\web2py\\applications\\BrainChaco\\controllers/PreguntasController.py'
p5
sS'code'
p6
S"# -*- coding: utf-8 -*-\n# intente algo como\ndef index():\n   \tpreguntas = db.executesql('SELECT descripcion FROM pregunta WHERE idcat=reques.args(0) ORDER BY RAND() LIMIT 1')\n   \tresponse.view='PreguntasController/index.html'\n   \treturn dict(preguntas=preguntas)\n\t\n\nresponse._vars=response._caller(index)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "D:\\web2py\\gluon\\restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "D:\\web2py\\applications\\BrainChaco\\controllers/PreguntasController.py", line 9, in <module>\n  File "D:\\web2py\\gluon\\globals.py", line 417, in <lambda>\n    self._caller = lambda f: f()\n  File "D:\\web2py\\applications\\BrainChaco\\controllers/PreguntasController.py", line 4, in index\n    preguntas = db.executesql(\'SELECT descripcion FROM pregunta WHERE idcat=reques.args(0) ORDER BY RAND() LIMIT 1\')\n  File "D:\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 1019, in executesql\n    adapter.execute(query)\n  File "D:\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 1388, in execute\n    return self.log_execute(*a, **b)\n  File "D:\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 1382, in log_execute\n    ret = self.get_cursor().execute(command, *a[1:], **b)\n  File "MySQLdb/cursors.py", line 205, in execute\n  File "MySQLdb/connections.py", line 36, in defaulterrorhandler\nOperationalError: (1305, \'FUNCTION reques.args does not exist\')\n'
p11
s.